"""
Stage 4 — Merge LoRA weights into the base model and save as a standalone model.

Why merge?
  LoRA keeps adapter weights separate from the base model during training.
  This is efficient (fewer params to update) but requires PEFT at inference time.
  Merging combines them into a single model that loads like any HuggingFace model
  — no PEFT dependency needed at serving time.

Output: artifacts/merged-model/
  This directory is loaded directly by the FastAPI serving API (Stage 5).
"""

import logging
from pathlib import Path

import torch
import yaml
from peft import PeftModel
from transformers import AutoModelForCausalLM, AutoTokenizer

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger(__name__)

with open("config/config.yaml") as f:
    CONFIG = yaml.safe_load(f)


def resolve_lora_dir(config_output_dir: str) -> str:
  """
  Resolve LoRA adapter directory.

  If adapter_config.json is not in output_dir, fall back to the newest
  checkpoint-* folder generated by trainer.
  """
  out = Path(config_output_dir)
  if (out / "adapter_config.json").exists():
    return str(out)

  candidates = sorted(
    [p for p in out.glob("checkpoint-*") if (p / "adapter_config.json").exists()],
    key=lambda p: int(p.name.split("-")[-1]),
  )
  if candidates:
    resolved = str(candidates[-1])
    logger.warning(
      f"LoRA adapter not found at '{config_output_dir}'. Using latest checkpoint: {resolved}"
    )
    return resolved

  raise FileNotFoundError(
    f"No adapter_config.json found in '{config_output_dir}' or checkpoint-* subfolders."
  )


def main():
    model_name = CONFIG["base_model"]["name"]
    lora_dir = resolve_lora_dir(CONFIG["training"]["output_dir"])
    merged_dir = CONFIG["export"]["merged_model_dir"]

    logger.info(f"Loading base model: {model_name}")
    base_model = AutoModelForCausalLM.from_pretrained(
        model_name,
        torch_dtype=torch.float32,
        device_map="cpu",     # merge on CPU to avoid MPS memory limits
    )

    logger.info(f"Loading LoRA adapter: {lora_dir}")
    model = PeftModel.from_pretrained(base_model, lora_dir)

    logger.info("Merging LoRA weights into base model...")
    model = model.merge_and_unload()

    logger.info(f"Saving merged model to: {merged_dir}")
    model.save_pretrained(merged_dir)

    tokenizer = AutoTokenizer.from_pretrained(model_name)
    tokenizer.save_pretrained(merged_dir)

    logger.info("Export complete. Model ready for serving.")


if __name__ == "__main__":
    main()
